services:

  coordinator:
    build:
      context: ..
      dockerfile: docker/coordinator/Dockerfile
    ports:
      - "5558:5558"   # ROUTER/DEALER
    environment:
      - COORDINATOR_HOST=${COORDINATOR_HOST}
    profiles: ["local", "coord"]

  edge:
    build:
      context: ..
      dockerfile: docker/edge/Dockerfile
    environment:
      - COORDINATOR_HOST=${COORDINATOR_HOST}
    cap_add:
      - NET_ADMIN
    profiles: ["local", "node"]

  sensor:
    build:
      context: ..
      dockerfile: docker/sensor/Dockerfile
    profiles: ["local", "node"]






